### ISSUE TITLE
! (Shell escape)

### ISSUE THREAD

**Issue by dashaw92** [mad4j/rogue.js#6]
Pressing the '!' key to escape to the shell appears to freeze the game.

**Comment by mad4j** [comment]
Fixed #6
- removed _HAVE_WORKING_FORK_ from `extern.h`
- preserved orginal game logic: `[Press return to continue]` requested, no shell will be opened
- if _EMSCRIPTEN_ is defined then the message `[Press return to continue]` also displayed using curses
